Styling the mass chown & chprem command.

diff --git a/bin/ffpog b/bin/ffpog
--- a/bin/ffpog
+++ b/bin/ffpog
@@ -1,8 +1,6 @@
 #!/bin/sh
 ########################################################################
 # Fix file permissions and ownership.
-# 
-#
 ########################################################################
 
 OPTIONS=$(getopt -n "$0" -o f:d:o:g:rv --long "file-permissions:,directory-permissions:,owner:,group:,recursive,verbose,dry-run" -- "$@")
@@ -20,10 +18,10 @@ VERBOSE="no"
 change_perm() {
     # CHMOD should never be empty!
     if [ "yes" = "$DRY_RUN" ]; then
-	echo "$CHMOD $2 $1"
+        echo "$CHMOD $2 $1"
     else
-	_echo "$CHMOD $2 $1"
-	$CHMOD $2 $1
+        _echo "$CHMOD $2 $1"
+        $CHMOD $2 $1
     fi
     
     return $?
@@ -32,14 +30,14 @@ change_perm() {
 change_owner() {
     # Owner does not change?
     if [ -z "$CHOWN" ]; then
-	return 0
+        return 0
     fi
     
     if [ "yes" = "$DRY_RUN" ]; then
-	echo "$CHOWN $1"
+        echo "$CHOWN $1"
     else
-	_echo "$CHOWN $1"
-	$CHOWN $1
+        _echo "$CHOWN $1"
+        $CHOWN $1
     fi
     
     return $?
@@ -52,19 +50,19 @@ fix_file_perms_owner() {
     change_perm "$__FILE" "$__PERM"
     RET=$?
     if [ ! 0 -eq "$RET" ]; then
-	exit $RET
+        exit $RET
     fi
 
     change_owner "$__FILE"
     RET=$?
     if [ ! 0 -eq "$RET" ]; then
-	exit 1;
+        exit 1;
     fi
 }
 
 _echo() {
     if [ "yes" = "$VERBOSE" ]; then
-	echo "$@"
+        echo "$@"
     fi
 }
 
@@ -75,50 +73,50 @@ eval set -- "$OPTIONS"
 
 while true ; do
     case "$1" in
-	-f|--file-permissions)
-	    if [ ! -z "$2" ]; then
-		FILE_PERM="$2"
-	    fi
-	    shift 2
-	    ;;
-	-d|--directory-permissions)
-	    if [ ! -z "$2" ]; then
-		DIR_PREM="$2"
-	    fi
-	    shift 2
-	    ;;
-	-o|--owner)
-	    if [ ! -z "$2" ]; then
-		OWNER="$2"
-	    fi
-	    shift 2
-	    ;;
-	-g|--group)
-	    if [ ! -z "$2" ]; then
-		GROUP="$2"
-	    fi
-	    shift 2
-	    ;;
-	-r|--recursive)
-	    RECURSIVE="yes"
-	    shift
-	    ;;
-	--dry-run)
-	    DRY_RUN="yes"
-	    shift
-	    ;;
-	-v|--verbose)
-	    VERBOSE="yes"
-	    shift
-	    ;;
-	--)
-	    shift
-	    break
-	    ;;
-	*)
-	    echo "$0: internal error!"
-	    exit 1
-	    ;;
+    -f|--file-permissions)
+        if [ ! -z "$2" ]; then
+            FILE_PERM="$2"
+        fi
+        shift 2
+        ;;
+    -d|--directory-permissions)
+        if [ ! -z "$2" ]; then
+            DIR_PREM="$2"
+        fi
+        shift 2
+        ;;
+    -o|--owner)
+        if [ ! -z "$2" ]; then
+            OWNER="$2"
+        fi
+        shift 2
+        ;;
+    -g|--group)
+        if [ ! -z "$2" ]; then
+            GROUP="$2"
+        fi
+        shift 2
+        ;;
+    -r|--recursive)
+        RECURSIVE="yes"
+        shift
+        ;;
+    --dry-run)
+        DRY_RUN="yes"
+        shift
+        ;;
+    -v|--verbose)
+        VERBOSE="yes"
+        shift
+        ;;
+    --)
+        shift
+        break
+        ;;
+    *)
+        echo "$0: internal error!"
+        exit 1
+        ;;
     esac
 done
 
@@ -157,43 +155,42 @@ fi
 
 for file; do
     if [ -d "$file" ]; then
-	
-	if [ "yes" = "$RECURSIVE" ]; then
-	    
-	    #ALL_DIRS=$(find "$file" -type d)
-	    #ALL_FILES=$(find "$file" -type f)
-	    
-	    # Find all subdirectories.
-	    for f in $(find "$file" -type d); do
-		fix_file_perms_owner "$f" "$DIR_PERM"
-	    done
-	    
-	    # Find all files in all subdirectories.
-	    for f in $(find "$file" -type f); do
-		fix_file_perms_owner "$f" "$FILE_PERM"
-	    done
-	    
-	else
-	    fix_file_perms_owner "$file" "$DIR_PERM"
-	fi
-	
-	# Onto the next file in the list.
-	continue
+    
+        if [ "yes" = "$RECURSIVE" ]; then
+            
+            #ALL_DIRS=$(find "$file" -type d)
+            #ALL_FILES=$(find "$file" -type f)
+            
+            # Find all subdirectories.
+            for f in $(find "$file" -type d); do
+                fix_file_perms_owner "$f" "$DIR_PERM"
+            done
+            
+            # Find all files in all subdirectories.
+            for f in $(find "$file" -type f); do
+                fix_file_perms_owner "$f" "$FILE_PERM"
+            done
+            
+        else
+            fix_file_perms_owner "$file" "$DIR_PERM"
+        fi
+        
+        # Onto the next file in the list.
+        continue
     fi
     
     # For regular files things are much easier.
     if [ -f "$file" ]; then
-	fix_file_perms_owner "$file" "$FILE_PERM"
-	# Onto the next file in the list.
-	continue
+        fix_file_perms_owner "$file" "$FILE_PERM"
+        # Onto the next file in the list.
+        continue
     fi
     
     # File not found? Report error and exit.
     if [ ! -a "$file" ]; then
-	echo "$0: file not found: ${file}"
-	exit 1
+        echo "$0: file not found: ${file}"
+        exit 1
     fi
 done
 
 exit 0
-
